### PR TITLE
Added Microapp functions

### PR DESCRIPTION
**Pull request by mPlagge**

### CODE REVIEW

**Comment by vliedel** [comment]
Hi, since the microapp functionality is not released in the firmware yet, the functions should be added as experimental. You can move the functions to the UsbDevHandler, that makes it clear these functions are for internal usage.

**Comment by mrquincle** [comment]
General remarks:

- Add description to your PR.
- Remove print in enable_microapp and add return code
- Check spelling (success).
- Comments are just describing what's happening next. It would be good to have proper descriptions above the functions about how they are used and what kind of errors can be returned rather than these oneliners. 

Some examples:

- Do we have to call validate before enable? 
- Can the user of this lib disable a microapp that is not enabled or do they get an error code in that case?
- Is there a choice for (a)sync made?
- What are the restrictions on the index parameter? Can it be 0? Can it be a billion?

Is there anything that should be considered to be implemented next?

Nice to have: if https://github.com/crownstone/crownstone-lib-python-uart/blob/master/DOCUMENTATION.md would look like https://github.com/crownstone/crownstone-lib-nodejs-cloud/blob/master/docs/CLOUD_API.md. Something for new PR. ;-)

**Comment by mPlagge** [comment]
I moved the functions to the UsbDevHandler class, and described the comments and documentation for the functions in more detail. I also fixed the spelling mistakes and return  code. @vliedel @mrquincle

**Comment by mrquincle** [comment]
Looks good. Check again spelling and punctuation of the docstrings. For example the docstring at validate_app doesn't start with a capital letter while the other docstrings do. 

The sentence "it doesn't check if the command is set correctly" is not clear. Do you mean that it doesn't check if the command is **received** correctly by bluenet? Or **executed** correctly by bluenet?

"Remove microapp from flash memory." Is the memory actually cleared? Or is only a reference removed? 

Is it necessary to remove the microapp before uploading a new one?

No "parameters" are "returns" are specified. I think it's easier to read if you would say something like:

```
    Parameters:
    index (int): Index of microapp starting at 0. Currently only a single microapp is supported. 
```

**Comment by vliedel** [comment]
It's better to use the self._send() method instead of wrapping it in every function.

And I see that the _send() method doesn't check the returned result yet, as it does in the ControlHandler. We can change that after the merge.

**Pull request merged**
